
FROM isaac-lab-base:latest

ARG USERNAME=harry
ARG USER_UID=1002
ARG USER_GID=1002


RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        nano \
        tmux \
        hdf5-tools \
        build-essential \
        cmake \
        git \
        libglib2.0-0 \
        ncurses-term \
        wget \
        sudo && \
    apt -y upgrade && \
    apt -y autoremove && \
    apt clean autoclean && \
    rm -rf /var/lib/apt/lists/*

RUN groupadd --gid $USER_GID $USERNAME && \
    useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
    usermod -aG sudo $USERNAME && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME

# --- Copy Isaac Lab and create symlink to Isaac Sim ---
COPY ../ ${ISAACLAB_PATH}

RUN --mount=type=cache,target=/var/cache/apt \
    ${ISAACLAB_PATH}/isaaclab.sh -p -m pip install toml && \
    ${ISAACLAB_PATH}/isaaclab.sh --install && \
    ${ISAACLAB_PATH}/isaaclab.sh -p ${ISAACLAB_PATH}/tools/install_deps.py apt ${ISAACLAB_PATH}/source && \
    ${ISAACLAB_PATH}/isaaclab.sh -p -m pip uninstall -y quadprog && \
    ${ISAACLAB_PATH}/isaaclab.sh -p -m pip install --upgrade --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 && \
    ${ISAACLAB_PATH}/isaaclab.sh -p -m pip install tensorflow scikit-learn robomimic==0.3.0 && \
    apt -y autoremove && \
    apt clean autoclean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR ${ISAACLAB_PATH}
