
FROM isaac-lab-base AS harry

ARG USERNAME=harry
ARG USER_UID=1002
ARG USER_GID=1002


RUN --mount=type=cache,target=/var/cache/apt \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        nano \
        tmux \
        hdf5-tools \
        git \
        sudo && \
    apt -y upgrade && \
    apt -y autoremove && \
    apt clean autoclean && \
    rm -rf /var/lib/apt/lists/*

RUN groupadd --gid $USER_GID $USERNAME && \
    useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
    usermod -aG sudo $USERNAME && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME

# --- Copy Isaac Lab and create symlink to Isaac Sim ---
COPY ../ ${ISAACLAB_PATH}

WORKDIR ${ISAACLAB_PATH}
